### ISSUE TITLE
How can I get the frame poses and global poses?

### ISSUE THREAD

**Issue by Tom-Zheng** [torrvision/CollaborativeSLAMDataset#3]
I noticed that both the reconstruct-global.sh and reconstruct-collaborative.sh read the pose for every frame from disk, by specifying the -t Disk argument. But how can I get these poses, e.g., for a new sequence? When I try to remove the -t Disk argument and instead use -t InfiniTAM tracker, the tracking was immediately lost after a few frames. I also have confusions on how do I get the global_poses.txt for a new dataset. Any advice on how I can reproduce the results or start from a new sequence?

**Comment by sgolodetz** [comment]
The sequences in the dataset were captured with an Asus ZenFone AR, which has a high-quality visual-inertial tracker built in. We implemented an app on the ZenFone to allow streaming of RGB-D frames and their poses to the desktop. If you don't have a ZenFone available (quite likely, since they sadly stopped making them), an alternative way of getting sufficiently accurate poses (as we showed in Section 4.5 in the paper) is to use something like BundleFusion (offline). More generally, any high-quality tracking approach (particularly an IMU-based one) should be ok, although that wasn't the focus of our paper. The ICP tracker in InfiniTAM is tolerable in general, but we found that it wasn't good enough for our needs here - it's quite hard to scan entire rooms with it without it failing at some point.

Regarding the global poses file - if you run the pipeline in collaborative mode, a suitable file will be saved on exit in the `global_poses` subdirectory. See also the `CollaborativePoseOptimiser::save_global_poses` function.
